//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveMemberHistory
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> MemberCode { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<int> BankCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public bool Rejoined { get; set; }
        public bool Resigned { get; set; }
        public Nullable<int> TotalMonthsPaid { get; set; }
        public Nullable<int> TotalMonthsDue { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public string MemberStatus { get; set; }
        public Nullable<int> MemberStatusCode { get; set; }
    }
}
