//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArrearPostMaster
    {
        public int ID { get; set; }
        public Nullable<decimal> MemberCode { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> BeforeLastPaymentDate { get; set; }
        public Nullable<decimal> BeforeTotalMonthsPaid { get; set; }
        public Nullable<System.DateTime> UpdatedEntryDate { get; set; }
        public Nullable<bool> IsEdited { get; set; }
        public Nullable<int> TotalDuePay { get; set; }
        public Nullable<decimal> BeforeTotalSubscription { get; set; }
        public Nullable<decimal> BeforeTotalBF { get; set; }
        public string UpdatedStatus { get; set; }
    }
}
