//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArrearPreDetail
    {
        public int ID { get; set; }
        public int MasterId { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<decimal> AmounBF { get; set; }
        public Nullable<decimal> AmountSubscription { get; set; }
        public string UpdatedStatus { get; set; }
        public Nullable<int> MemberCode { get; set; }
    }
}
