//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTHSTRY
    {
        public int Id { get; set; }
        public string MemberCode { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public string BeforeBranchCode { get; set; }
        public string ModifiedBranchCode { get; set; }
    }
}
