//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventHistory
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FormName { get; set; }
        public Nullable<int> Event { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string BeforeData { get; set; }
        public string ModifiedData { get; set; }
        public string TableName { get; set; }
        public string Remarks { get; set; }
    }
}
