//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTERBANKBRANCH
    {
        public decimal BANKBRANCH_CODE { get; set; }
        public Nullable<decimal> BANK_CODE { get; set; }
        public string BANKBRANCH_NAME { get; set; }
        public string BANKBRANCH_USERCODE { get; set; }
        public string BANKBRANCH_ADDRESS1 { get; set; }
        public string BANKBRANCH_ADDRESS2 { get; set; }
        public string BANKBRANCH_ADDRESS3 { get; set; }
        public Nullable<decimal> BANKBRANCH_CITY_CODE { get; set; }
        public Nullable<decimal> BANKBRANCH_STATE_CODE { get; set; }
        public string BANKBRANCH_COUNTRY { get; set; }
        public string BANKBRANCH_ZIPCODE { get; set; }
        public string BANKBRANCH_PHONE1 { get; set; }
        public string BANKBRANCH_PHONE2 { get; set; }
        public string BANKBRANCH_EMAIL { get; set; }
        public Nullable<decimal> NUBE_BRANCH_CODE { get; set; }
        public Nullable<decimal> DELETED { get; set; }
        public Nullable<decimal> HEAD_QUARTERS { get; set; }
        public Nullable<decimal> MERGED { get; set; }
    }
}
