//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTERNUBEBRANCH
    {
        public decimal NUBE_BRANCH_CODE { get; set; }
        public string NUBE_BRANCH_USERCODE { get; set; }
        public string NUBE_BRANCH_NAME { get; set; }
        public Nullable<decimal> DELETED { get; set; }
    }
}
