//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTERSTATU
    {
        public decimal STATUS_CODE { get; set; }
        public string STATUS_NAME { get; set; }
        public string STATUS_SHORTCODE { get; set; }
        public Nullable<decimal> DELETED { get; set; }
    }
}
