//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipAttachment
    {
        public int Id { get; set; }
        public Nullable<int> MemberCode { get; set; }
        public string AttachmentName { get; set; }
        public byte[] AttachmentData { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
