//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomineeInsertBranch
    {
        public decimal MEMBER_CODE { get; set; }
        public string ICNO_OLD { get; set; }
        public string ICNO_NEW { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public Nullable<decimal> AGE { get; set; }
        public Nullable<decimal> RELATION_CODE { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public Nullable<decimal> CITY_CODE { get; set; }
        public Nullable<decimal> STATE_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE { get; set; }
        public string MOBILE { get; set; }
        public Nullable<decimal> USER_CODE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string ENTRY_TIME { get; set; }
        public int Id { get; set; }
    }
}
