//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESIGNATION
    {
        public decimal MEMBER_CODE { get; set; }
        public Nullable<System.DateTime> RESIGNATION_DATE { get; set; }
        public Nullable<decimal> RESIGNSTATUS_CODE { get; set; }
        public string ICNO { get; set; }
        public string ICNO_OLD { get; set; }
        public Nullable<decimal> RELATION_CODE { get; set; }
        public Nullable<decimal> REASON_CODE { get; set; }
        public string CLAIMER_NAME { get; set; }
        public Nullable<decimal> MONTHS_CONTRIBUTED { get; set; }
        public Nullable<decimal> ACCBF { get; set; }
        public Nullable<decimal> ACCBENEFIT { get; set; }
        public string CHEQUENO { get; set; }
        public Nullable<System.DateTime> CHEQUEDATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> TOTALARREARS { get; set; }
        public Nullable<decimal> USER_CODE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string ENTRY_TIME { get; set; }
        public Nullable<System.DateTime> CURRENTDATE { get; set; }
        public Nullable<System.DateTime> VOUCHER_DATE { get; set; }
        public Nullable<decimal> SERVICE_YEAR { get; set; }
        public int Id { get; set; }
        public string PayMode { get; set; }
        public Nullable<decimal> InsuranceAmount { get; set; }
    }
}
