//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempGE
    {
        public int Id { get; set; }
        public Nullable<int> MEMBER_CODE { get; set; }
        public Nullable<int> MEMBER_ID { get; set; }
        public string GE_ICNO { get; set; }
        public string CONTRACTNO { get; set; }
    }
}
