//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountGroup
    {
        public decimal AccountGroupId { get; set; }
        public string GroupName { get; set; }
        public string GroupCode { get; set; }
        public string Under { get; set; }
        public Nullable<decimal> ProfitAndLoss { get; set; }
    }
}
