//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class AI_Insurance
    {
        public int Id { get; set; }
        public Nullable<int> MemberCode { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> PolicyNo { get; set; }
        public Nullable<int> MbrNo { get; set; }
        public Nullable<int> DpntNo { get; set; }
        public Nullable<int> Member { get; set; }
        public string MemberName { get; set; }
        public string ICNO { get; set; }
        public string Rel { get; set; }
        public string Sex { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string CostCenter { get; set; }
        public string InternetAddress { get; set; }
        public string BankCode { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Age { get; set; }
        public string StaffID { get; set; }
        public Nullable<System.DateTime> EmployDate { get; set; }
        public Nullable<int> MasterMember { get; set; }
        public string MasterName { get; set; }
        public string MasterIC { get; set; }
        public Nullable<System.DateTime> EffDate { get; set; }
        public string SubStd { get; set; }
        public string Takeover { get; set; }
        public string Coverage { get; set; }
    }
}
