//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger
    {
        public decimal LedgerId { get; set; }
        public string LedgerName { get; set; }
        public string BillingName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string MailId { get; set; }
        public string CreditDays { get; set; }
        public string CreditLimit { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> AccountGroupId { get; set; }
        public string AccountCode { get; set; }
        public Nullable<double> CrAmt { get; set; }
        public Nullable<double> DrAmt { get; set; }
    }
}
