//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTERRESIGNSTATU
    {
        public decimal RESIGNSTATUS_CODE { get; set; }
        public string RESIGNSTATUS_NAME { get; set; }
        public string RESIGNSTATUS_SHORTCODE { get; set; }
        public Nullable<decimal> RESIGNSTATUS_EXPELLED { get; set; }
        public Nullable<decimal> DELETED { get; set; }
        public Nullable<bool> IsBenefitValid { get; set; }
        public Nullable<int> MinimumYear { get; set; }
        public Nullable<int> MinimumRefund { get; set; }
        public Nullable<int> MaximumRefund { get; set; }
        public Nullable<decimal> AmtPerYear1 { get; set; }
        public Nullable<decimal> AmtPerYear2 { get; set; }
    }
}
