//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterMemberStatu
    {
        public int Id { get; set; }
        public Nullable<int> FeeYear { get; set; }
        public Nullable<int> FeeMonth { get; set; }
        public Nullable<decimal> MEMBER_CODE { get; set; }
        public Nullable<decimal> MEMBERTYPE_CODE { get; set; }
        public Nullable<decimal> BANK_CODE { get; set; }
        public Nullable<decimal> BRANCH_CODE { get; set; }
        public Nullable<decimal> NUBE_BRANCH_CODE { get; set; }
        public Nullable<decimal> SUBSCRIPTION_AMOUNT { get; set; }
        public Nullable<decimal> BF_AMOUNT { get; set; }
        public Nullable<System.DateTime> LASTPAYMENTDATE { get; set; }
        public Nullable<decimal> TOTALSUBCRP_AMOUNT { get; set; }
        public Nullable<decimal> TOTALBF_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_MONTHS { get; set; }
        public string ENTRYMODE { get; set; }
        public string DEFAULTINGMONTHS { get; set; }
        public Nullable<decimal> TOTALMONTHSDUE { get; set; }
        public Nullable<decimal> TOTALMONTHSPAID { get; set; }
        public Nullable<decimal> SUBSCRIPTIONDUE { get; set; }
        public Nullable<decimal> BFDUE { get; set; }
        public Nullable<decimal> ACCSUBSCRIPTION { get; set; }
        public Nullable<decimal> ACCBF { get; set; }
        public Nullable<decimal> ACCBENEFIT { get; set; }
        public Nullable<decimal> CURRENT_YDTBF { get; set; }
        public Nullable<decimal> CURRENT_YDTSUBSCRIPTION { get; set; }
        public Nullable<decimal> STATUS_CODE { get; set; }
        public Nullable<decimal> RESIGNED { get; set; }
        public Nullable<decimal> CANCELLED { get; set; }
        public Nullable<decimal> USER_CODE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string ENTRY_TIME { get; set; }
        public Nullable<decimal> STRUCKOFF { get; set; }
    }
}
