//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTERMEMBERNEW
    {
        public int MEMBER_CODE { get; set; }
        public string MEMBER_NAME { get; set; }
        public string MEMBER_ID { get; set; }
        public string MEMBER_TITLE { get; set; }
        public string BF_NO { get; set; }
        public string ICNO_OLD { get; set; }
        public string ICNO_NEW { get; set; }
        public int BANK_CODE { get; set; }
        public int BRANCH_CODE { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public Nullable<int> CITY_CODE { get; set; }
        public Nullable<int> STATE_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DATEOFJOINING { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
        public Nullable<int> AGE_IN_YEARS { get; set; }
        public Nullable<System.DateTime> DATEOFEMPLOYMENT { get; set; }
        public Nullable<int> MEMBERTYPE_CODE { get; set; }
        public bool SEX { get; set; }
        public Nullable<int> RACE_CODE { get; set; }
        public bool REJOINED { get; set; }
        public Nullable<int> STATUS_CODE { get; set; }
        public Nullable<int> PREVIOUS_STATUSCODE { get; set; }
        public string LEVY { get; set; }
        public Nullable<decimal> LEVY_AMOUNT { get; set; }
        public Nullable<System.DateTime> LevyPaymentDate { get; set; }
        public string TDF { get; set; }
        public Nullable<decimal> TDF_AMOUNT { get; set; }
        public Nullable<System.DateTime> Tdf_PaymentDate { get; set; }
        public Nullable<int> TOTALMONTHSPAID { get; set; }
        public Nullable<decimal> ENTRANCEFEE { get; set; }
        public Nullable<decimal> BatchAmt { get; set; }
        public Nullable<decimal> HQFEE { get; set; }
        public Nullable<decimal> MONTHLYBF { get; set; }
        public Nullable<decimal> MONTHLYSUBSCRIPTION { get; set; }
        public Nullable<decimal> ACCBF { get; set; }
        public Nullable<decimal> ACCSUBSCRIPTION { get; set; }
        public Nullable<decimal> ACCBENEFIT { get; set; }
        public Nullable<decimal> CURRENT_YTDBF { get; set; }
        public Nullable<decimal> CURRENT_YTDSUBSCRIPTION { get; set; }
        public bool RESIGNED { get; set; }
        public Nullable<decimal> REGISTRATION_FEE { get; set; }
        public Nullable<System.DateTime> LASTPAYMENT_DATE { get; set; }
        public bool BLACKLISTED { get; set; }
        public string BLACKLISTREASON { get; set; }
        public bool STRUCKOFF { get; set; }
        public string STRUCKOFF_REMARKS { get; set; }
        public Nullable<System.DateTime> STRUCKOFF_DATE { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string MemberName_ByBank { get; set; }
        public string NRIC_ByBank { get; set; }
        public Nullable<int> BankCode_ByBank { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<System.DateTime> CancelOn { get; set; }
        public int CancelBy { get; set; }
        public bool AI_Insurance { get; set; }
        public string AI_MemberNo { get; set; }
        public Nullable<bool> GE_Insurance { get; set; }
        public string GE_ContractNo { get; set; }
        public int BranchMemberCode { get; set; }
        public Nullable<System.DateTime> ResignationDate { get; set; }
    }
}
