//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTERMEMBERNEW
    {
        public int MEMBER_CODE { get; set; }
        public int BANK_CODE { get; set; }
        public int BRANCH_CODE { get; set; }
        public Nullable<int> NUBE_BRANCH_CODE { get; set; }
        public Nullable<System.DateTime> DATEOFJOINING { get; set; }
        public bool REJOINED { get; set; }
        public Nullable<int> MEMBERTYPE_CODE { get; set; }
        public Nullable<System.DateTime> ResignationDate { get; set; }
        public Nullable<int> STATUS_CODE { get; set; }
        public Nullable<int> TOTALMONTHSPAID { get; set; }
        public Nullable<decimal> MONTHLYBF { get; set; }
        public Nullable<decimal> MONTHLYSUBSCRIPTION { get; set; }
        public Nullable<decimal> ACCBF { get; set; }
        public Nullable<decimal> ACCSUBSCRIPTION { get; set; }
        public Nullable<decimal> ACCBENEFIT { get; set; }
        public Nullable<decimal> CURRENT_YTDBF { get; set; }
        public Nullable<decimal> CURRENT_YTDSUBSCRIPTION { get; set; }
        public bool RESIGNED { get; set; }
        public Nullable<System.DateTime> LASTPAYMENT_DATE { get; set; }
        public bool STRUCKOFF { get; set; }
    }
}
