//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTERNUBEBRANCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTERNUBEBRANCH()
        {
            this.MASTERBANKBRANCHes = new HashSet<MASTERBANKBRANCH>();
        }
    
        public decimal NUBE_BRANCH_CODE { get; set; }
        public string NUBE_BRANCH_USERCODE { get; set; }
        public string NUBE_BRANCH_NAME { get; set; }
        public Nullable<decimal> DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTERBANKBRANCH> MASTERBANKBRANCHes { get; set; }
    }
}
