//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTERNAMESETUP
    {
        public string ORGANISATION_NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE { get; set; }
        public Nullable<System.DateTime> CUTOFFDATE { get; set; }
        public string VERSION { get; set; }
        public string SERVERNAME { get; set; }
        public string NEWEXEPATH { get; set; }
        public string NEWREPORTSPATH { get; set; }
        public string NEWIMAGESPATH { get; set; }
        public Nullable<decimal> EnterenceFees { get; set; }
        public Nullable<decimal> BuildingFund { get; set; }
        public Nullable<decimal> BF { get; set; }
        public Nullable<decimal> Subscription { get; set; }
        public Nullable<decimal> MembersContribution { get; set; }
        public Nullable<decimal> NUBEsContribution { get; set; }
        public Nullable<decimal> Insurance { get; set; }
        public Nullable<decimal> BadgeAmount { get; set; }
        public Nullable<decimal> LevyAmount { get; set; }
        public Nullable<decimal> TDFAmount { get; set; }
        public Nullable<decimal> RejoinAmount { get; set; }
        public string SenderEmailId { get; set; }
        public string SenderPassword { get; set; }
        public string CCEamilId1 { get; set; }
        public string CCEamilId2 { get; set; }
        public string PrinterName { get; set; }
        public string BackUpPath { get; set; }
    }
}
