//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberTransfer
    {
        public int Id { get; set; }
        public Nullable<decimal> MemberCode { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<decimal> BankCodeBF { get; set; }
        public Nullable<decimal> BranchCodeBF { get; set; }
        public Nullable<decimal> BankCodeAF { get; set; }
        public Nullable<decimal> BranchCodeAF { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
