//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberInsertBranch
    {
        public decimal MEMBER_CODE { get; set; }
        public string MEMBER_NAME { get; set; }
        public Nullable<decimal> MEMBER_ID { get; set; }
        public string MEMBER_TITLE { get; set; }
        public string ICNO_OLD { get; set; }
        public string ICNO_NEW { get; set; }
        public Nullable<decimal> BANK_CODE { get; set; }
        public Nullable<decimal> BANKBRANCH_CODE { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public Nullable<decimal> CITY_CODE { get; set; }
        public Nullable<decimal> STATE_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DATEOFJOINING { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
        public Nullable<decimal> AGE_IN_YEARS { get; set; }
        public Nullable<System.DateTime> DATEOFEMPLOYMENT { get; set; }
        public Nullable<decimal> MEMBERTYPE_CODE { get; set; }
        public string SEX { get; set; }
        public Nullable<decimal> RACE_CODE { get; set; }
        public Nullable<decimal> REJOINED { get; set; }
        public string LEVY { get; set; }
        public Nullable<decimal> TOTALMONTHSPAID { get; set; }
        public Nullable<decimal> ENTRANCEFEE { get; set; }
        public Nullable<decimal> HQFEE { get; set; }
        public Nullable<decimal> MONTHLYBF { get; set; }
        public Nullable<decimal> MONTHLYSUBSCRIPTION { get; set; }
        public Nullable<decimal> ACCBF { get; set; }
        public Nullable<decimal> ACCSUBSCRIPTION { get; set; }
        public Nullable<decimal> ACCBENEFIT { get; set; }
        public Nullable<decimal> CURRENT_YTDBF { get; set; }
        public Nullable<decimal> CURRENT_YTDSUBSCRIPTION { get; set; }
        public Nullable<decimal> RESIGNED { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<double> BatchAmt { get; set; }
        public Nullable<decimal> LEVY_AMOUNT { get; set; }
        public string TDF { get; set; }
        public Nullable<decimal> TDF_AMOUNT { get; set; }
        public Nullable<System.DateTime> LevyPaymentDate { get; set; }
        public Nullable<System.DateTime> Tdf_PaymentDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int IsApproved { get; set; }
        public string Occupation { get; set; }
    }
}
