//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlySubscriptionBankAttachment
    {
        public int Id { get; set; }
        public int MonthlySubscriptonBankId { get; set; }
        public int MonthlySubscriptionFileTypeId { get; set; }
        public string FilePath { get; set; }
        public byte[] FileContent { get; set; }
    
        public virtual MonthlySubscriptionBank MonthlySubscriptionBank { get; set; }
        public virtual MonthlySubscriptonFileType MonthlySubscriptonFileType { get; set; }
    }
}
