//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlySubscriptionBank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonthlySubscriptionBank()
        {
            this.MonthlySubscriptionBankAttachments = new HashSet<MonthlySubscriptionBankAttachment>();
            this.MonthlySubscriptionMembers = new HashSet<MonthlySubscriptionMember>();
        }
    
        public int Id { get; set; }
        public int MonthlySubscriptionId { get; set; }
        public decimal BankCode { get; set; }
        public decimal MatchedAmount { get; set; }
        public decimal NotMatchAmount { get; set; }
        public decimal StruckOffAmount { get; set; }
        public decimal ResignedAmount { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual MonthlySubscription MonthlySubscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlySubscriptionBankAttachment> MonthlySubscriptionBankAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlySubscriptionMember> MonthlySubscriptionMembers { get; set; }
        public virtual MASTERBANK MASTERBANK { get; set; }
    }
}
