//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlySubscriptionMemberUpdate
    {
        public int Id { get; set; }
        public Nullable<decimal> MemberCode { get; set; }
        public Nullable<decimal> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> MonthlySubscriptionMatchingTypeId { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    
        public virtual MASTERMEMBER MASTERMEMBER { get; set; }
        public virtual MonthlySubscriptionMatchingType MonthlySubscriptionMatchingType { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
