//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlySubscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonthlySubscription()
        {
            this.MonthlySubscriptionBanks = new HashSet<MonthlySubscriptionBank>();
        }
    
        public int Id { get; set; }
        public System.DateTime date { get; set; }
        public decimal MatchedAmount { get; set; }
        public decimal NotMatchAmount { get; set; }
        public decimal StruckOffAmount { get; set; }
        public decimal ResignedAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public bool MonthEndClosed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlySubscriptionBank> MonthlySubscriptionBanks { get; set; }
    }
}
