//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public decimal ProductId { get; set; }
        public string ProductName { get; set; }
        public string ItemCode { get; set; }
        public decimal GroupId { get; set; }
        public Nullable<double> SellingRate { get; set; }
        public Nullable<double> PurchaseRate { get; set; }
        public decimal UOMId { get; set; }
        public Nullable<double> ReOrderLevel { get; set; }
        public Nullable<double> OpQty { get; set; }
        public string Tax { get; set; }
    }
}
