//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderDetail
    {
        public decimal SODId { get; set; }
        public decimal SOId { get; set; }
        public decimal ProductId { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Quantity { get; set; }
        public decimal UOMId { get; set; }
        public decimal TaxId { get; set; }
        public Nullable<double> DisPer { get; set; }
    }
}
