//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusModify
    {
        public int Id { get; set; }
        public int MemberCode { get; set; }
        public Nullable<int> OldStatusCode { get; set; }
        public Nullable<int> NewStatusCode { get; set; }
        public Nullable<int> UserCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedStatus { get; set; }
    }
}
