//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nubebfsstatusEntities : DbContext
    {
        public nubebfsstatusEntities()
            : base("name=nubebfsstatusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STATUS012017> STATUS012017 { get; set; }
        public virtual DbSet<STATUS012018> STATUS012018 { get; set; }
        public virtual DbSet<STATUS022017> STATUS022017 { get; set; }
        public virtual DbSet<STATUS022018> STATUS022018 { get; set; }
        public virtual DbSet<STATUS032017> STATUS032017 { get; set; }
        public virtual DbSet<STATUS032018> STATUS032018 { get; set; }
        public virtual DbSet<STATUS042016> STATUS042016 { get; set; }
        public virtual DbSet<STATUS042017> STATUS042017 { get; set; }
        public virtual DbSet<STATUS042018> STATUS042018 { get; set; }
        public virtual DbSet<STATUS052016> STATUS052016 { get; set; }
        public virtual DbSet<STATUS052017> STATUS052017 { get; set; }
        public virtual DbSet<STATUS052018> STATUS052018 { get; set; }
        public virtual DbSet<STATUS062016> STATUS062016 { get; set; }
        public virtual DbSet<STATUS062017> STATUS062017 { get; set; }
        public virtual DbSet<STATUS062018> STATUS062018 { get; set; }
        public virtual DbSet<STATUS072016> STATUS072016 { get; set; }
        public virtual DbSet<STATUS072017> STATUS072017 { get; set; }
        public virtual DbSet<STATUS072018> STATUS072018 { get; set; }
        public virtual DbSet<STATUS082016> STATUS082016 { get; set; }
        public virtual DbSet<STATUS082017> STATUS082017 { get; set; }
        public virtual DbSet<STATUS082018> STATUS082018 { get; set; }
        public virtual DbSet<STATUS092016> STATUS092016 { get; set; }
        public virtual DbSet<STATUS092017> STATUS092017 { get; set; }
        public virtual DbSet<STATUS092018> STATUS092018 { get; set; }
        public virtual DbSet<STATUS102016> STATUS102016 { get; set; }
        public virtual DbSet<STATUS102017> STATUS102017 { get; set; }
        public virtual DbSet<STATUS102018> STATUS102018 { get; set; }
        public virtual DbSet<STATUS112016> STATUS112016 { get; set; }
        public virtual DbSet<STATUS112017> STATUS112017 { get; set; }
        public virtual DbSet<STATUS112018> STATUS112018 { get; set; }
        public virtual DbSet<STATUS122016> STATUS122016 { get; set; }
        public virtual DbSet<STATUS122017> STATUS122017 { get; set; }
        public virtual DbSet<STATUS122018> STATUS122018 { get; set; }
        public virtual DbSet<FEE_STATUS> FEE_STATUS { get; set; }
        public virtual DbSet<FEE_STATUS_UPTO_1980> FEE_STATUS_UPTO_1980 { get; set; }
        public virtual DbSet<FEE_STATUS_UPTO_1985> FEE_STATUS_UPTO_1985 { get; set; }
        public virtual DbSet<FEE_STATUS_UPTO_1990> FEE_STATUS_UPTO_1990 { get; set; }
        public virtual DbSet<FEE_STATUS_UPTO_1995> FEE_STATUS_UPTO_1995 { get; set; }
        public virtual DbSet<FEE_STATUS_UPTO_2000> FEE_STATUS_UPTO_2000 { get; set; }
        public virtual DbSet<FEE_STATUS_UPTO_2005> FEE_STATUS_UPTO_2005 { get; set; }
        public virtual DbSet<FEE_STATUS_UPTO_2010> FEE_STATUS_UPTO_2010 { get; set; }
        public virtual DbSet<FEE_STATUS_UPTO_2016> FEE_STATUS_UPTO_2016 { get; set; }
    }
}
