//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tran_Start
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<System.DateTime> MonthEnd { get; set; }
        public Nullable<System.DateTime> MonthEndUpdatedOn { get; set; }
        public Nullable<System.DateTime> YearEnd { get; set; }
        public Nullable<System.DateTime> YearEndUpdatedOn { get; set; }
    }
}
