//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERMASTER
    {
        public decimal USER_CODE { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<decimal> ADMIN_RIGHTS { get; set; }
        public Nullable<decimal> FIRSTUSER { get; set; }
        public Nullable<decimal> DELETED { get; set; }
    }
}
