//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWTOTALDUE
    {
        public decimal MEMBER_CODE { get; set; }
        public Nullable<System.DateTime> LASTPAIDDATE { get; set; }
        public Nullable<decimal> TOTALMOTHSDUE { get; set; }
        public Nullable<int> TOTALDUE { get; set; }
        public Nullable<decimal> TOTALDUEPAY { get; set; }
    }
}
