//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLedgerReceipt
    {
        public Nullable<decimal> VoucherID { get; set; }
        public string VoucherType { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string LedgerName { get; set; }
        public string LedgerNameOP { get; set; }
        public string Narration { get; set; }
        public Nullable<double> DrAmt { get; set; }
        public Nullable<double> CrAmt { get; set; }
        public string VoucherNo { get; set; }
        public string VoucherName { get; set; }
        public string Fund { get; set; }
        public string LedgerNameOP2 { get; set; }
        public string ChequeNo { get; set; }
    }
}
