//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewResign
    {
        public Nullable<System.DateTime> RESIGNATION_DATE { get; set; }
        public Nullable<decimal> RESIGNSTATUS_CODE { get; set; }
        public string ICNO_OLD { get; set; }
        public string ICNO { get; set; }
        public Nullable<decimal> RELATION_CODE { get; set; }
        public string RELATION_NAME { get; set; }
        public Nullable<decimal> REASON_CODE { get; set; }
        public string RESIGNSTATUS_NAME { get; set; }
        public string RESIGNSTATUS_SHORTCODE { get; set; }
        public string CLAIMER_NAME { get; set; }
        public Nullable<decimal> MONTHS_CONTRIBUTED { get; set; }
        public Nullable<decimal> ACCBF { get; set; }
        public Nullable<decimal> ACCBENEFIT { get; set; }
        public string CHEQUENO { get; set; }
        public Nullable<System.DateTime> CHEQUEDATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> TOTALARREARS { get; set; }
        public Nullable<decimal> USER_CODE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string ENTRY_TIME { get; set; }
        public Nullable<System.DateTime> CURRENTDATE { get; set; }
        public Nullable<System.DateTime> VOUCHER_DATE { get; set; }
        public Nullable<decimal> SERVICE_YEAR { get; set; }
        public Nullable<decimal> MEMBER_CODE { get; set; }
        public string MEMBER_NAME { get; set; }
        public Nullable<decimal> MEMBER_ID { get; set; }
        public string MEMBER_TITLE { get; set; }
        public string MEMBER_INITIAL { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_USERCODE { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY_NAME { get; set; }
        public string STATE_NAME { get; set; }
        public string COUNTRY { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DATEOFJOINING { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
        public Nullable<decimal> AGE_IN_YEARS { get; set; }
        public string MEMBERTYPE_NAME { get; set; }
        public string BRANCHNAME { get; set; }
        public string BRANCHUSERCODE { get; set; }
        public Nullable<int> MONDUE { get; set; }
        public Nullable<int> ContributedMonth { get; set; }
        public string NUBEBRANCH { get; set; }
        public string NUBEBANCHNAME { get; set; }
        public Nullable<decimal> MONTHLYBF { get; set; }
        public Nullable<System.DateTime> LASTPAYMENT_DATE { get; set; }
        public string PAYMODE { get; set; }
        public Nullable<decimal> InsuranceAmount { get; set; }
    }
}
