//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewBranch
    {
        public decimal BANKBRANCH_CODE { get; set; }
        public Nullable<decimal> BANK_CODE { get; set; }
        public string BANKBRANCH_ADDRESS1 { get; set; }
        public string BANKBRANCH_ADDRESS2 { get; set; }
        public string BANKBRANCH_ADDRESS3 { get; set; }
        public string CITY_NAME { get; set; }
        public string STATE_NAME { get; set; }
        public string BANKBRANCH_COUNTRY { get; set; }
        public string BANKBRANCH_ZIPCODE { get; set; }
        public string BANKBRANCH_PHONE1 { get; set; }
        public string BANKBRANCH_PHONE2 { get; set; }
        public string BANKBRANCH_EMAIL { get; set; }
    }
}
