//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMasterMember
    {
        public decimal MEMBER_CODE { get; set; }
        public string MEMBER_NAME { get; set; }
        public Nullable<decimal> MEMBER_ID { get; set; }
        public string MEMBER_TITLE { get; set; }
        public string MEMBER_INITIAL { get; set; }
        public string ICNO_OLD { get; set; }
        public string ICNO_NEW { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_USERCODE { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY_NAME { get; set; }
        public string STATE_NAME { get; set; }
        public string COUNTRY { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DATEOFJOINING { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
        public Nullable<decimal> AGE_IN_YEARS { get; set; }
        public Nullable<System.DateTime> DATEOFEMPLOYMENT { get; set; }
        public string MEMBERTYPE_NAME { get; set; }
        public string SEX { get; set; }
        public string RACE_NAME { get; set; }
        public Nullable<decimal> REJOINED { get; set; }
        public string STATUS_NAME { get; set; }
        public Nullable<int> TOTALMONTHSPAID { get; set; }
        public Nullable<decimal> ENTRANCEFEE { get; set; }
        public Nullable<decimal> HQFEE { get; set; }
        public Nullable<decimal> MONTHLYBF { get; set; }
        public Nullable<decimal> MONTHLYSUBSCRIPTION { get; set; }
        public Nullable<decimal> ACCBF { get; set; }
        public Nullable<decimal> ACCSUBSCRIPTION { get; set; }
        public Nullable<decimal> ACCBENEFIT { get; set; }
        public Nullable<decimal> CURRENT_YTDBF { get; set; }
        public Nullable<decimal> CURRENT_YTDSUBSCRIPTION { get; set; }
        public Nullable<decimal> RESIGNED { get; set; }
        public Nullable<System.DateTime> LASTPAYMENT_DATE { get; set; }
        public Nullable<decimal> STRUCKOFF { get; set; }
        public Nullable<decimal> BANK_CODE { get; set; }
        public Nullable<decimal> BRANCH_CODE { get; set; }
        public Nullable<decimal> CITY_CODE { get; set; }
        public Nullable<decimal> STATE_CODE { get; set; }
        public Nullable<decimal> MEMBERTYPE_CODE { get; set; }
        public Nullable<decimal> RACE_CODE { get; set; }
        public Nullable<decimal> STATUS_CODE { get; set; }
        public string BRANCHNAME { get; set; }
        public string BRANCHADR1 { get; set; }
        public string BRANCHADR2 { get; set; }
        public string BRANCHADR3 { get; set; }
        public string BRANCHCITY { get; set; }
        public string BRANCHSTATE { get; set; }
        public string BRANCHUSERCODE { get; set; }
        public string MEMBERSTATUS { get; set; }
        public int MEMBERSTATUSCODE { get; set; }
        public Nullable<int> MONDUE { get; set; }
        public string NUBEBRANCH { get; set; }
        public string BRANCHZIPCODE { get; set; }
        public string NUBEBANCHNAME { get; set; }
        public string NUBEBANCHCODE { get; set; }
        public Nullable<double> BATCHAMT { get; set; }
        public Nullable<int> TOTALMOTHSDUE { get; set; }
        public string LEVY { get; set; }
        public string MEMBERNAME_BYBANK { get; set; }
        public string NRIC_BYBANK { get; set; }
        public decimal BANKCODE_BYBANK { get; set; }
        public decimal LEVY_AMOUNT { get; set; }
        public decimal TDF_AMOUNT { get; set; }
        public string TDF { get; set; }
        public System.DateTime RESIGNATION_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public Nullable<System.DateTime> VOUCHER_DATE { get; set; }
        public bool ISCANCEL { get; set; }
        public bool AI_INSURANCE { get; set; }
        public bool GE_INSURANCE { get; set; }
    }
}
