//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLedger
    {
        public decimal LedgerId { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LedgerName { get; set; }
        public string LedgerNameOP { get; set; }
        public string Particulars { get; set; }
        public string Narration { get; set; }
        public Nullable<double> CRAmount { get; set; }
        public Nullable<double> DRAmount { get; set; }
        public string GroupName { get; set; }
        public string GroupCode { get; set; }
        public string RootGroup { get; set; }
        public string BillingName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string MailId { get; set; }
        public string CreditDays { get; set; }
        public string Note { get; set; }
        public string CreditLimit { get; set; }
        public Nullable<decimal> AccountGroupId { get; set; }
        public string AccountCode { get; set; }
        public string AcNo { get; set; }
    }
}
