//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWRESIGNREPORT
    {
        public Nullable<long> RNO { get; set; }
        public Nullable<decimal> MEMBER_CODE { get; set; }
        public Nullable<decimal> MEMBER_ID { get; set; }
        public string MEMBER_NAME { get; set; }
        public Nullable<System.DateTime> DATEOFJOINING { get; set; }
        public Nullable<System.DateTime> RESIGNATION_DATE { get; set; }
        public string ICNO { get; set; }
        public Nullable<System.DateTime> VOUCHER_DATE { get; set; }
        public string NUBEBRANCH { get; set; }
        public string BANK { get; set; }
        public Nullable<decimal> ACCBF { get; set; }
        public Nullable<decimal> ACCBENEFIT { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string CHEQUENO { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string RESIGNSTATUS_CODE { get; set; }
        public Nullable<decimal> STATUSCODE { get; set; }
        public string CLAIMER_NAME { get; set; }
        public string NUBEBANCHNAME { get; set; }
        public string BANK_NAME { get; set; }
        public string BRANCHNAME { get; set; }
    }
}
