//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewStockReport
    {
        public decimal VoucherCode { get; set; }
        public string VoucherType { get; set; }
        public string LedgerName { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public string ItemName { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Rate { get; set; }
        public string UOM { get; set; }
        public Nullable<double> Amount { get; set; }
        public double TaxPer { get; set; }
        public Nullable<double> TaxAmt { get; set; }
        public Nullable<double> DisPer { get; set; }
        public Nullable<double> DisAmt { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string RootGroup { get; set; }
    }
}
