//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPurchaseSearch
    {
        public decimal PurchaseId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string SupplierName { get; set; }
        public string PurchaseType { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<double> Extra { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public string Narration { get; set; }
        public Nullable<double> TotalAmount { get; set; }
    }
}
