//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSalesReturn
    {
        public decimal SRId { get; set; }
        public Nullable<System.DateTime> SRDate { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string SRType { get; set; }
        public Nullable<double> Extra { get; set; }
        public string Narration { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public Nullable<double> ItemAmount { get; set; }
        public Nullable<double> BillAmount { get; set; }
    }
}
