//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLedgerPurchase
    {
        public decimal VocherCode { get; set; }
        public string VocherType { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LedgerName { get; set; }
        public string Particulars { get; set; }
        public string Narration { get; set; }
        public Nullable<double> CRAmount { get; set; }
        public Nullable<double> DRAmount { get; set; }
        public string RootGroup { get; set; }
    }
}
