//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMembership
    {
        public decimal MEMBER_CODE { get; set; }
        public string MEMBER_NAME { get; set; }
        public Nullable<decimal> MEMBER_ID { get; set; }
        public string MEMBER_TITLE { get; set; }
        public string MEMBER_INITIAL { get; set; }
        public Nullable<decimal> BF_NO { get; set; }
        public string ICNO_OLD { get; set; }
        public string ICNO_NEW { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_USERCODE { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY_NAME { get; set; }
        public string STATE_NAME { get; set; }
        public string COUNTRY { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DATEOFJOINING { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
        public Nullable<decimal> AGE_IN_YEARS { get; set; }
        public Nullable<System.DateTime> DATEOFEMPLOYMENT { get; set; }
        public string MEMBERTYPE_NAME { get; set; }
        public string SEX { get; set; }
        public string RACE_NAME { get; set; }
        public string PROPOSEDBY { get; set; }
        public Nullable<decimal> REJOINED { get; set; }
        public Nullable<decimal> PROPOSED_MEMBERID { get; set; }
        public string SECONDEDBY { get; set; }
        public Nullable<decimal> SECONDED_MEMBERID { get; set; }
        public string CONFIRMEDAT { get; set; }
        public Nullable<System.DateTime> HELDON { get; set; }
        public string STATUS_NAME { get; set; }
        public Nullable<decimal> TOTALMONTHSPAID { get; set; }
        public Nullable<decimal> ENTRANCEFEE { get; set; }
        public Nullable<decimal> HQFEE { get; set; }
        public Nullable<decimal> MONTHLYBF { get; set; }
        public Nullable<decimal> MONTHLYSUBSCRIPTION { get; set; }
        public Nullable<decimal> ACCBF { get; set; }
        public Nullable<decimal> ACCSUBSCRIPTION { get; set; }
        public Nullable<decimal> ACCBENEFIT { get; set; }
        public Nullable<decimal> CURRENT_YTDBF { get; set; }
        public Nullable<decimal> CURRENT_YTDSUBSCRIPTION { get; set; }
        public Nullable<decimal> RESIGNED { get; set; }
        public string PAYMENT_MODE { get; set; }
        public Nullable<decimal> USER_CODE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string ENTRY_TIME { get; set; }
        public Nullable<decimal> REGISTRATION_FEE { get; set; }
        public Nullable<System.DateTime> LASTPAYMENT_DATE { get; set; }
        public Nullable<decimal> BLACKLISTED { get; set; }
        public string BLACKLISTREASON { get; set; }
        public string DATEOFBIRTH_S { get; set; }
        public string DATEOFEMPLOYMENT_S { get; set; }
        public Nullable<decimal> STRUCKOFF { get; set; }
        public string STRUCKOFF_REMARKS { get; set; }
        public Nullable<System.DateTime> STRUCKOFF_DATE { get; set; }
        public Nullable<System.DateTime> WAIVERDATE { get; set; }
        public string WAIVERREASON { get; set; }
        public Nullable<decimal> BANK_CODE { get; set; }
        public Nullable<decimal> BRANCH_CODE { get; set; }
        public Nullable<decimal> CITY_CODE { get; set; }
        public Nullable<decimal> STATE_CODE { get; set; }
        public Nullable<decimal> MEMBERTYPE_CODE { get; set; }
        public Nullable<decimal> RACE_CODE { get; set; }
        public Nullable<decimal> STATUS_CODE { get; set; }
        public string BRANCHNAME { get; set; }
        public string BRANCHADR1 { get; set; }
        public string BRANCHADR2 { get; set; }
        public string BRANCHADR3 { get; set; }
        public string BRANCHCITY { get; set; }
        public string BRANCHSTATE { get; set; }
        public string BRANCHUSERCODE { get; set; }
        public string MEMBERSTATUS { get; set; }
        public int MEMBERSTATUSCODE { get; set; }
        public Nullable<decimal> MONDUE { get; set; }
        public string NUBEBRANCH { get; set; }
        public string BRANCHZIPCODE { get; set; }
        public string NUBEBANCHNAME { get; set; }
        public string NUBEBANCHCODE { get; set; }
        public Nullable<double> BATCHAMT { get; set; }
        public Nullable<decimal> TOTALMOTHSDUE { get; set; }
        public string LEVY { get; set; }
        public string MEMBERNAME_BYBANK { get; set; }
        public string NRIC_BYBANK { get; set; }
        public decimal BANKCODE_BYBANK { get; set; }
    }
}
