//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWNOMINEE
    {
        public int ID { get; set; }
        public decimal MEMBER_CODE { get; set; }
        public string NAME { get; set; }
        public decimal AGE { get; set; }
        public string SEX { get; set; }
        public string RELATION_NAME { get; set; }
        public string ICNO_NEW { get; set; }
        public string ICNO_OLD { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY_NAME { get; set; }
        public string STATE_NAME { get; set; }
        public string MOBILE { get; set; }
        public string PHONE { get; set; }
        public decimal CITY_CODE { get; set; }
        public decimal STATE_CODE { get; set; }
        public decimal RELATION_CODE { get; set; }
    }
}
