//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewBankBranch
    {
        public decimal BranchCode { get; set; }
        public Nullable<decimal> BANK_CODE { get; set; }
        public string BankName { get; set; }
        public string BANK_USERCODE { get; set; }
        public string BranchName { get; set; }
        public string BranchUserCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<decimal> BANKBRANCH_CITY_CODE { get; set; }
        public string CityName { get; set; }
        public Nullable<decimal> BANKBRANCH_STATE_CODE { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string EMail { get; set; }
        public Nullable<decimal> NUBE_BRANCH_CODE { get; set; }
        public string NubeBanchCode { get; set; }
        public string NubeBanchName { get; set; }
        public Nullable<decimal> DELETED { get; set; }
        public Nullable<decimal> HEAD_QUARTERS { get; set; }
        public Nullable<decimal> MERGED { get; set; }
        public string StateName { get; set; }
    }
}
