//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nube
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTrialBalance
    {
        public Nullable<decimal> MEMBER_ID { get; set; }
        public string MEMBER_NAME { get; set; }
        public string ICNO { get; set; }
        public string BankCode { get; set; }
        public Nullable<decimal> TOTALMONTHSPAID { get; set; }
        public Nullable<decimal> ACCBF { get; set; }
        public Nullable<System.DateTime> LASTPAYMENTDATE { get; set; }
        public string MEMBERTYPE_NAME { get; set; }
        public string MemberStatus { get; set; }
        public string NubeBanchName { get; set; }
    }
}
